### ISSUE TITLE
Possible missing dependency (chokidar)

### ISSUE THREAD

**Issue by ewann** [francoislaberge/diagrams#8]
I encountered the following while investigating diagrams. I'm unsure if this is an environmental issue on my side. Certainly chokidar is not listed in whats currently at: https://github.com/francoislaberge/diagrams/blob/master/package.json

```
# sudo npm install -g diagrams
```
/usr/local/bin/diagrams -> /usr/local/lib/node_modules/diagrams/bin/diagrams.js
/usr/local/lib
└── diagrams@0.8.1 
```
# diagrams watch
```
module.js:472
    throw err;
    ^
Error: Cannot find module 'chokidar'
```
# sudo npm install -g chokidar
```
/usr/local/lib
└─┬ chokidar@1.6.1 
  ├─┬ anymatch@1.3.0 
  │ ├── arrify@1.0.1 
  │ └─┬ micromatch@2.3.11 
  │   ├─┬ arr-diff@2.0.0 
  │   │ └── arr-flatten@1.0.1 
  │   ├── array-unique@0.2.1 
  │   ├─┬ braces@1.8.5 
  │   │ ├─┬ expand-range@1.8.2 
  │   │ │ └─┬ fill-range@2.2.3 
  │   │ │   ├── is-number@2.1.0 
  │   │ │   ├── isobject@2.1.0 
  │   │ │   ├── randomatic@1.1.6 
  │   │ │   └── repeat-string@1.6.1 
  │   │ ├── preserve@0.2.0 
  │   │ └── repeat-element@1.1.2 
  │   ├─┬ expand-brackets@0.1.5 
  │   │ └── is-posix-bracket@0.1.1 
  │   ├── extglob@0.3.2 
  │   ├── filename-regex@2.0.0 
  │   ├─┬ kind-of@3.1.0 
  │   │ └── is-buffer@1.1.4 
  │   ├── normalize-path@2.0.1 
  │   ├─┬ object.omit@2.0.1 
  │   │ ├─┬ for-own@0.1.4 
  │   │ │ └── for-in@0.1.6 
  │   │ └── is-extendable@0.1.1 
  │   ├─┬ parse-glob@3.0.4 
  │   │ ├── glob-base@0.3.0 
  │   │ └── is-dotfile@1.0.2 
  │   └─┬ regex-cache@0.4.3 
  │     ├── is-equal-shallow@0.1.3 
  │     └── is-primitive@2.0.0 
  ├── async-each@1.0.1 
  ├── glob-parent@2.0.0 
  ├── inherits@2.0.3 
  ├─┬ is-binary-path@1.0.1 
  │ └── binary-extensions@1.8.0 
  ├─┬ is-glob@2.0.1 
  │ └── is-extglob@1.0.0 
  ├── path-is-absolute@1.0.1 
  └─┬ readdirp@2.1.0 
    ├── graceful-fs@4.1.11 
    ├─┬ minimatch@3.0.3 
    │ └─┬ brace-expansion@1.1.6 
    │   ├── balanced-match@0.4.2 
    │   └── concat-map@0.0.1 
    ├─┬ readable-stream@2.2.2 
    │ ├── buffer-shims@1.0.0 
    │ ├── core-util-is@1.0.2 
    │ ├── isarray@1.0.0 
    │ ├── process-nextick-args@1.0.7 
    │ ├── string_decoder@0.10.31 
    │ └── util-deprecate@1.0.2 
    └── set-immediate-shim@1.0.1 
```
# diagrams watch
```
infrastructure-manual.dot -> infrastructure-manual.dot.svg

```
# npm -v
```
4.0.5

```
# lsb_release -a
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by francoislaberge** [comment]
Thanks, I must have missed adding it. Surprised no one ever mentioned it. Should be fixed in:
https://github.com/francoislaberge/diagrams/releases/tag/v0.8.2
